### ISSUE TITLE
how to make circles appear close and how to handle that in project

### ISSUE THREAD

**Issue by hemapanjakshram** [sreeharikv112/ViewPagerIndicator#1]
i m referring this project and code is in java but for me distance/gap between circle looks to be slightly more so can u let me know how to reduce the distance/gap between circles provided android:thickness remains
 same?

**Comment by sreeharikv112** [comment]
You can change to change values of **app:tabPaddingStart**  and  **app:tabPaddingEnd** to reduce the distance/gap between circles.


```
<com.google.android.material.tabs.TabLayout
            android:id="@+id/into_tab_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:tabBackground="@drawable/tab_pager_selector"
            app:tabGravity="center"
            app:tabPaddingStart="5dp"
            app:tabPaddingEnd="5dp"
            app:tabIndicatorHeight="0dp"
            android:layout_gravity="bottom"
    />
```
@hemapanjakshram Can you test and confirm from your end.

Below will be the indicators as per above changes..


<img width="331" alt="Screenshot 2020-10-14 at 12 26 05 PM" src="https://user-images.githubusercontent.com/39777674/95954143-7b907200-0e18-11eb-901f-cc9e7e37ca24.png">
